{% set name = "curtsies" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 102a0ffbf952124f1be222fd6989da4ec7cce04e49f613009e5f54ad37618825

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<310]
  # ModuleNotFoundError: No module named 'termios'
  # https://docs.python.org/3/library/tty.html
  # Because it requires the termios module, it will work only on Unix.
  # Issue created: https://github.com/bpython/curtsies/issues/178
  skip: True  # [win]

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools >=46.4.0
  run:
    - python
    - blessed >=1.5
    - cwcwidth

test:
  source_files:
    - tests
  imports:
    - curtsies
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - pytest
    - pyte

about:
  home: https://github.com/bpython/curtsies
  summary: Curses-like terminal wrapper, with colored strings!
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    Curtsies is a Python 3.6+ compatible library for interacting with the terminal.
  dev_url: https://github.com/bpython/curtsies
  doc_url: https://github.com/bpython/curtsies/tree/main/docs

extra:
  recipe-maintainers:
    - scopatz
    - mariusvniekerk
